#cloud-config
users:
  - name: ubuntu
    roups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTQw5uluvWM/WumzF42TKEemU41kfvhi9mG1Zjss3j7qhEpS2eC7K142IcjDnfYiDwmWBClsgHayidNy9Iyt7uqy8T3kLwVMEfCPSc8Kaa8pzaflbn+Et7tHHacwq87HAQDFbcHRGgfQNEn4+7CG/uqPSmprZTNddFj1zXLCLZ2hwfX3Gd4+Jp21JLM7w/7jzpBA6J+eqZUmw6W6UJogPyA2YmWq8mhmRzo4WGdbIbU9XrzcrNkcKHrK7ka0XIytZ0YIAbCcBV9vZUEvFi/PkB1PkCa/fVZbXcdULwMKYF0cD5B6pOOGsvethfWbMweOfrU9dbM36CySpqE7b/AN6F3oASkaDk9DvOUqnD2MlEw4dqPPmURM0iPVDBYgtSwRgpwgyGhBuMbewnnZdsAeGizXONn3SVtx5Y/HBON7fakLOCggCQ6qG4iXVo7XCDmCSi4x87oF7iD5IcnXuAE4zjEogEltVxvBOz3Wm3Wof/fcNVxChNfyIDeBCPl8UpMhU= vladimir@master
runcmd:
  - sudo chmod 777 /var/www/html/index.html
  - echo "<html><head><title>Hello</title></head><body><h1>Hello</h1><p>Hostname=$(hostname)</p><p>ip=$(curl https://ipinfo.io/ip)</p> <p><a href=\"https://bucket-vladimir-$(date '+%d-%m-%Y').storage.yandexcloud.net/image.jpg\">My-picture</a></p></body></html>" > /var/www/html/index.html
